### ISSUE TITLE
iterm configuration file?

### ISSUE THREAD

**Issue by ildoonet** [sublee/sublette#1]
Need a drop-in configuration file for iterm. It'll make this repository much accessible for people.

**Comment by sublee** [comment]
Thanks for the suggestion.

I tried to generate [a configuration for iTerm2](https://github.com/sublee/sublette/tree/master/configs/iTerm2) but now I can't check the quality of it due to lack of macOS. I'll check tomorrow.

**Comment by sublee** [comment]
It's done. Try with the current version of [Sublette.itermcolors](https://raw.githubusercontent.com/sublee/sublette/master/configs/iTerm2/Sublette.itermcolors).
